# ใช้ Python base image
FROM python:3.11-slim

# ตั้ง working directory
WORKDIR /app

# คัดลอกไฟล์ requirements
COPY requirements.txt .

# ติดตั้ง dependencies
RUN pip install --no-cache-dir -r requirements.txt

# คัดลอกโค้ดทั้งหมด
COPY . .

# คัดลอกไฟล์ CSV ไปยัง /tmp
COPY data/data.csv /tmp/
COPY data/favorite.csv /tmp/
COPY data/fetch_date.csv /tmp/
COPY data/filtered.csv /tmp/
# รัน FastAPI ด้วย uvicorn
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8080"]
